
/**
 * ***** DO NOT EDIT THIS FILE MANUALLY *****
 * This file is generated automatically by the Reaction
 * plugin loader and will be reset at each startup.
 */

import '/imports/plugins/core/checkout/server';
import '/imports/plugins/core/dashboard/server';
import '/imports/plugins/core/layout/server';
import '/imports/plugins/core/orders/server';
import '/imports/plugins/core/revisions/server';
import '/imports/plugins/core/shipping/server';
import '/imports/plugins/core/taxes/server';
import '/imports/plugins/core/ui/server';
import '/imports/plugins/core/ui-navbar/server';
import '/imports/plugins/core/versions/server';
import '/imports/plugins/included/analytics/server';
import '/imports/plugins/included/authnet/server';
import '/imports/plugins/included/braintree/server';
import '/imports/plugins/included/example-paymentmethod/server';
import '/imports/plugins/included/inventory/server';
import '/imports/plugins/included/jobcontrol/server';
import '/imports/plugins/included/launchdock-connect/server';
import '/imports/plugins/included/paypal/server';
import '/imports/plugins/included/search-mongo/server';
import '/imports/plugins/included/social/server';
import '/imports/plugins/included/stripe/server';
import '/imports/plugins/included/taxes-avalara/server';
import '/imports/plugins/included/taxes-taxcloud/server';
import '/imports/plugins/included/taxes-taxjar/server';
import '/imports/plugins/core/checkout/register.js';
import '/imports/plugins/core/dashboard/register.js';
import '/imports/plugins/core/email/register.js';
import '/imports/plugins/core/layout/register.js';
import '/imports/plugins/core/orders/register.js';
import '/imports/plugins/core/revisions/register.js';
import '/imports/plugins/core/shipping/register.js';
import '/imports/plugins/core/taxes/register.js';
import '/imports/plugins/core/ui/register.js';
import '/imports/plugins/core/ui-grid/register.js';
import '/imports/plugins/core/ui-navbar/register.js';
import '/imports/plugins/core/ui-tagnav/register.js';
import '/imports/plugins/core/versions/register.js';
import '/imports/plugins/included/analytics/register.js';
import '/imports/plugins/included/authnet/register.js';
import '/imports/plugins/included/braintree/register.js';
import '/imports/plugins/included/default-theme/register.js';
import '/imports/plugins/included/example-paymentmethod/register.js';
import '/imports/plugins/included/inventory/register.js';
import '/imports/plugins/included/jobcontrol/register.js';
import '/imports/plugins/included/launchdock-connect/register.js';
import '/imports/plugins/included/paypal/register.js';
import '/imports/plugins/included/product-admin/register.js';
import '/imports/plugins/included/product-detail-simple/register.js';
import '/imports/plugins/included/product-variant/register.js';
import '/imports/plugins/included/search-mongo/register.js';
import '/imports/plugins/included/social/register.js';
import '/imports/plugins/included/stripe/register.js';
import '/imports/plugins/included/taxes-avalara/register.js';
import '/imports/plugins/included/taxes-taxcloud/register.js';
import '/imports/plugins/included/ui-search/register.js';
import '/imports/plugins/custom/reaction-example-theme/register.js';
